public with sharing class DistributedRevenue {
    @AuraEnabled
    public Id id;
    @AuraEnabled
    public Id AccountId;
    @AuraEnabled
    public Id OpportunityId;
    @AuraEnabled
    public String AccountName;
    @AuraEnabled
    public String OpportunityName;
    @AuraEnabled
    public String Name;
    @AuraEnabled
    public Decimal Jan;
    @AuraEnabled
    public Decimal Feb;
    @AuraEnabled
    public Decimal Mar;
    @AuraEnabled
    public Decimal Apr;
    @AuraEnabled
    public Decimal May;
    @AuraEnabled
    public Decimal June;
    @AuraEnabled
    public Decimal July;
    @AuraEnabled
    public Decimal Aug;
    @AuraEnabled
    public Decimal Sep;
    @AuraEnabled
    public Decimal Oct;
    @AuraEnabled
    public Decimal Nov;
    @AuraEnabled
    public Decimal Dec;
}